---
- name: Get the list of mounted filesystems
  shell: set -o pipefail && cat /proc/mounts | awk '{ print $2}' | grep -E "^{{ mounted_fs }}"
  register: get_mounted_filesystems
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: get_mounted_filesystems.stdout | length > 0
  check_mode: false
  # with_items: # in main.yml -> Umount k3s filesystems
  #   - /run/k3s
  #   - /var/lib/kubelet
  #   - /run/netns
  #   - /var/lib/rancher/k3s
  #   - /var/lib/kubelet/pods
  #   - /var/lib/kubelet/plugins
  #   - /run/netns/cni-

- name: Umount filesystem
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items:
    "{{ get_mounted_filesystems.stdout_lines | reverse | list }}"